import { Exercise } from "@/components/AddExerciseModal";

export const chestExercises: Exercise[] = [
  {
    id: "chest-1",
    name: "Barbell Bench Press",
    category: "Chest",
    type: "Barbell",
  },
  {
    id: "chest-2",
    name: "Incline Barbell Bench Press",
    category: "Chest",
    type: "Barbell",
  },
  {
    id: "chest-3",
    name: "Decline Barbell Bench Press",
    category: "Chest",
    type: "Barbell",
  },
  {
    id: "chest-4",
    name: "Dumbbell Bench Press",
    category: "Chest",
    type: "Dumbbell",
  },
  {
    id: "chest-5",
    name: "Incline Dumbbell Bench Press",
    category: "Chest",
    type: "Dumbbell",
  },
  {
    id: "chest-6",
    name: "Decline Dumbbell Bench Press",
    category: "Chest",
    type: "Dumbbell",
  },
  {
    id: "chest-7",
    name: "Dumbbell Flyes",
    category: "Chest",
    type: "Dumbbell",
  },
  {
    id: "chest-8",
    name: "Incline Dumbbell Flyes",
    category: "Chest",
    type: "Dumbbell",
  },
  {
    id: "chest-9",
    name: "Decline Dumbbell Flyes",
    category: "Chest",
    type: "Dumbbell",
  },
  {
    id: "chest-10",
    name: "Cable Flyes",
    category: "Chest",
    type: "Cable",
  },
  {
    id: "chest-11",
    name: "Incline Cable Flyes",
    category: "Chest",
    type: "Cable",
  },
  {
    id: "chest-12",
    name: "Decline Cable Flyes",
    category: "Chest",
    type: "Cable",
  },
  {
    id: "chest-13",
    name: "Chest Dips",
    category: "Chest",
    type: "Bodyweight",
  },
  {
    id: "chest-14",
    name: "Pec Deck Flyes",
    category: "Chest",
    type: "Machine",
  },
  {
    id: "chest-15",
    name: "Cable Crossover",
    category: "Chest",
    type: "Cable",
  },
  {
    id: "chest-16",
    name: "Smith Machine Bench Press",
    category: "Chest",
    type: "Machine",
  },
  {
    id: "chest-17",
    name: "Incline Smith Machine Bench Press",
    category: "Chest",
    type: "Machine",
  },
  {
    id: "chest-18",
    name: "Decline Smith Machine Bench Press",
    category: "Chest",
    type: "Machine",
  },
  {
    id: "chest-19",
    name: "Close-Grip Barbell Bench Press",
    category: "Chest",
    type: "Barbell",
  },
  {
    id: "chest-20",
    name: "Decline Dumbbell Press",
    category: "Chest",
    type: "Dumbbell",
  },
  {
    id: "chest-21",
    name: "Seated Machine Chest Press",
    category: "Chest",
    type: "Machine",
  },
  {
    id: "chest-22",
    name: "Incline Cable Press",
    category: "Chest",
    type: "Cable",
  },
  {
    id: "chest-23",
    name: "Decline Cable Press",
    category: "Chest",
    type: "Cable",
  },
  {
    id: "chest-24",
    name: "Standing Cable Flyes",
    category: "Chest",
    type: "Cable",
  },
  {
    id: "chest-25",
    name: "Plyometric Push-ups",
    category: "Chest",
    type: "Bodyweight",
  },
  {
    id: "chest-26",
    name: "Svend Press",
    category: "Chest",
    type: "Plate",
  },
];

export const backExercises: Exercise[] = [
  {
    id: "back-1",
    name: "Pull-ups",
    category: "Back",
    type: "Bodyweight",
  },
  {
    id: "back-2",
    name: "Chin-ups",
    category: "Back",
    type: "Bodyweight",
  },
  {
    id: "back-3",
    name: "Barbell Rows",
    category: "Back",
    type: "Barbell",
  },
  {
    id: "back-4",
    name: "Dumbbell Rows",
    category: "Back",
    type: "Dumbbell",
  },
  {
    id: "back-5",
    name: "Seated Cable Rows",
    category: "Back",
    type: "Cable",
  },
  {
    id: "back-6",
    name: "Lat Pulldowns",
    category: "Back",
    type: "Machine",
  },
  {
    id: "back-7",
    name: "T-Bar Rows",
    category: "Back",
    type: "Barbell",
  },
  {
    id: "back-8",
    name: "Face Pulls",
    category: "Back",
    type: "Cable",
  },
  {
    id: "back-9",
    name: "Deadlifts",
    category: "Back",
    type: "Barbell",
  },
  {
    id: "back-10",
    name: "Hyperextensions",
    category: "Back",
    type: "Bodyweight",
  },
  {
    id: "back-11",
    name: "Rack Pulls",
    category: "Back",
    type: "Barbell",
  },
  {
    id: "back-12",
    name: "Inverted Rows",
    category: "Back",
    type: "Bodyweight",
  },
  {
    id: "back-13",
    name: "Chest Supported Dumbbell Rows",
    category: "Back",
    type: "Dumbbell",
  },
];

export const legsExercises: Exercise[] = [
  {
    id: "legs-1",
    name: "Barbell Squats",
    category: "Legs",
    type: "Barbell",
  },
  {
    id: "legs-2",
    name: "Front Squats",
    category: "Legs",
    type: "Barbell",
  },
  {
    id: "legs-3",
    name: "Leg Press",
    category: "Legs",
    type: "Machine",
  },
  {
    id: "legs-4",
    name: "Leg Extensions",
    category: "Legs",
    type: "Machine",
  },
  {
    id: "legs-5",
    name: "Hamstring Curls",
    category: "Legs",
    type: "Machine",
  },
  {
    id: "legs-6",
    name: "Romanian Deadlifts",
    category: "Legs",
    type: "Barbell",
  },
  {
    id: "legs-7",
    name: "Walking Lunges",
    category: "Legs",
    type: "Dumbbell",
  },
  {
    id: "legs-8",
    name: "Calf Raises",
    category: "Legs",
    type: "Bodyweight",
  },
  {
    id: "legs-9",
    name: "Glute Bridges",
    category: "Legs",
    type: "Bodyweight",
  },
  {
    id: "legs-10",
    name: "Step-ups",
    category: "Legs",
    type: "Bodyweight",
  },
  {
    id: "legs-11",
    name: "Hack Squats",
    category: "Legs",
    type: "Machine",
  },
  {
    id: "legs-12",
    name: "Bulgarian Split Squats",
    category: "Legs",
    type: "Dumbbell",
  },
  {
    id: "legs-13",
    name: "Hip Thrusts",
    category: "Legs",
    type: "Barbell",
  },
];

export const shouldersExercises: Exercise[] = [
  {
    id: "shoulders-1",
    name: "Overhead Press",
    category: "Shoulders",
    type: "Barbell",
  },
  {
    id: "shoulders-2",
    name: "Dumbbell Shoulder Press",
    category: "Shoulders",
    type: "Dumbbell",
  },
  {
    id: "shoulders-3",
    name: "Lateral Raises",
    category: "Shoulders",
    type: "Dumbbell",
  },
  {
    id: "shoulders-4",
    name: "Front Raises",
    category: "Shoulders",
    type: "Dumbbell",
  },
  {
    id: "shoulders-5",
    name: "Rear Delt Flyes",
    category: "Shoulders",
    type: "Dumbbell",
  },
  {
    id: "shoulders-6",
    name: "Arnold Press",
    category: "Shoulders",
    type: "Dumbbell",
  },
  {
    id: "shoulders-7",
    name: "Upright Rows",
    category: "Shoulders",
    type: "Barbell",
  },
  {
    id: "shoulders-8",
    name: "Face Pulls",
    category: "Shoulders",
    type: "Cable",
  },
  {
    id: "shoulders-9",
    name: "Cable Lateral Raises",
    category: "Shoulders",
    type: "Cable",
  },
  {
    id: "shoulders-10",
    name: "Push Press",
    category: "Shoulders",
    type: "Barbell",
  },
  {
    id: "shoulders-11",
    name: "Seated Dumbbell Shoulder Press",
    category: "Shoulders",
    type: "Dumbbell",
  },
  {
    id: "shoulders-12",
    name: "Front Plate Raises",
    category: "Shoulders",
    type: "Plate",
  },
];

export const armsExercises: Exercise[] = [
  {
    id: "arms-1",
    name: "Barbell Curls",
    category: "Arms",
    type: "Barbell",
  },
  {
    id: "arms-2",
    name: "Dumbbell Curls",
    category: "Arms",
    type: "Dumbbell",
  },
  {
    id: "arms-3",
    name: "Hammer Curls",
    category: "Arms",
    type: "Dumbbell",
  },
  {
    id: "arms-4",
    name: "Concentration Curls",
    category: "Arms",
    type: "Dumbbell",
  },
  {
    id: "arms-5",
    name: "Triceps Dips",
    category: "Arms",
    type: "Bodyweight",
  },
  {
    id: "arms-6",
    name: "Close-Grip Bench Press",
    category: "Arms",
    type: "Barbell",
  },
  {
    id: "arms-7",
    name: "Overhead Triceps Extensions",
    category: "Arms",
    type: "Dumbbell",
  },
  {
    id: "arms-8",
    name: "Triceps Pushdowns",
    category: "Arms",
    type: "Cable",
  },
  {
    id: "arms-9",
    name: "Skullcrushers",
    category: "Arms",
    type: "Barbell",
  },
  {
    id: "arms-10",
    name: "Preacher Curls",
    category: "Arms",
    type: "Barbell",
  },
  {
    id: "arms-11",
    name: "Cable Curls",
    category: "Arms",
    type: "Cable",
  },
  {
    id: "arms-12",
    name: "Reverse Curls",
    category: "Arms",
    type: "Barbell",
  },
];

export const coreExercises: Exercise[] = [
  {
    id: "core-1",
    name: "Plank",
    category: "Core",
    type: "Bodyweight",
  },
  {
    id: "core-2",
    name: "Crunches",
    category: "Core",
    type: "Bodyweight",
  },
  {
    id: "core-3",
    name: "Leg Raises",
    category: "Core",
    type: "Bodyweight",
  },
  {
    id: "core-4",
    name: "Russian Twists",
    category: "Core",
    type: "Bodyweight",
  },
  {
    id: "core-5",
    name: "Dead Bug",
    category: "Core",
    type: "Bodyweight",
  },
  {
    id: "core-6",
    name: "Hanging Leg Raises",
    category: "Core",
    type: "Bodyweight",
  },
  {
    id: "core-7",
    name: "Cable Woodchops",
    category: "Core",
    type: "Cable",
  },
  {
    id: "core-8",
    name: "Bird Dog",
    category: "Core",
    type: "Bodyweight",
  },
  {
    id: "core-9",
    name: "Side Plank",
    category: "Core",
    type: "Bodyweight",
  },
  {
    id: "core-10",
    name: "Bicycle Crunches",
    category: "Core",
    type: "Bodyweight",
  },
  {
    id: "core-11",
    name: "Ab Wheel Rollouts",
    category: "Core",
    type: "Equipment",
  },
  {
    id: "core-12",
    name: "Reverse Crunches",
    category: "Core",
    type: "Bodyweight",
  },
];

export const cardioExercises: Exercise[] = [
  {
    id: "cardio-1",
    name: "Running",
    category: "Cardio",
    type: "Activity",
  },
  {
    id: "cardio-2",
    name: "Cycling",
    category: "Cardio",
    type: "Activity",
  },
  {
    id: "cardio-3",
    name: "Swimming",
    category: "Cardio",
    type: "Activity",
  },
  {
    id: "cardio-4",
    name: "Jumping Jacks",
    category: "Cardio",
    type: "Other",
  },
  {
    id: "cardio-5",
    name: "Burpees",
    category: "Cardio",
    type: "Bodyweight",
  },
  {
    id: "cardio-6",
    name: "High Knees",
    category: "Cardio",
    type: "Bodyweight",
  },
  {
    id: "cardio-7",
    name: "Rowing",
    category: "Cardio",
    type: "Machine",
  },
  {
    id: "cardio-8",
    name: "Stair Climbing",
    category: "Cardio",
    type: "Machine",
  },
  {
    id: "cardio-9",
    name: "Elliptical Training",
    category: "Cardio",
    type: "Machine",
  },
  {
    id: "cardio-10",
    name: "Sprinting",
    category: "Cardio",
    type: "Activity",
  },
  {
    id: "cardio-11",
    name: "Battle Ropes",
    category: "Cardio",
    type: "Equipment",
  },
  {
    id: "cardio-12",
    name: "Box Jumps",
    category: "Cardio",
    type: "Other",
  },
];
